# Application Identity
spring.application.name=invitation-notification-service
server.port=8082

# Database - MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/notificationdb

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


spring.cloud.config.enabled=false
